import { useState } from 'react';
import { ArrowDown, Check, ChevronDown, GitBranch } from 'lucide-react';
import { models, type DecisionTrace } from '../shared/contracts';

const questions = [
  ['model', 'Model selection'], ['effort', 'Thinking effort'], ['taskType', 'Task type'], ['budgetModel', 'Budget option'],
] as const;
type QuestionKey = (typeof questions)[number][0];
const percent = (value: number) => `${(value * 100).toFixed(1).replace(/\.0$/, '')}%`;
function label(choice: string) {
  return models.find(model => model.id === choice)?.name ?? ({ none: 'No budget alternative', low: 'Low effort', medium: 'Medium effort', high: 'High effort' }[choice] ?? choice);
}

export function DecisionDetails({ trace }: { trace: DecisionTrace }) {
  const [active, setActive] = useState<QuestionKey>('model');
  const [showAll, setShowAll] = useState(false);
  const answer = trace.response.answers[active];
  const question = trace.request.questions[active];
  const options = Object.entries(question.criteria).map(([key, criterion]) => ({ key, criterion, probability: answer.probabilities?.[key] }));
  options.sort((a, b) => (b.probability ?? -1) - (a.probability ?? -1));
  const top = options.slice(0, 5);
  if (!top.some(option => option.key === answer.choice)) {
    const selected = options.find(option => option.key === answer.choice);
    if (selected) top.splice(4, 1, selected);
  }
  const visible = showAll ? options : top;

  return <section id="decision-details" className="decision-details" aria-labelledby="decision-title">
    <div className="trace-heading"><div><span className="small-label"><GitBranch size={15} /> YOUR CONSORT SHOWS HIS WORK</span><h2 id="decision-title">Why Jev introduced you.</h2></div><span className="trace-live"><Check size={14} /> Actual API response</span></div>
    <p className="trace-intro">Chemistry is nice. Receipts are better. These are Jev’s original selections and scores—not compatibility ratings, and not changed by your swipes.</p>
    <div className="trace-context"><span>Priority <strong>{trace.request.state.priority === 'balanced' ? 'Task fit' : trace.request.state.priority}</strong></span><span>Catalog <strong>{Object.keys(trace.request.questions.model.criteria).length} models</strong></span><span>Verified <strong>{trace.catalogVerifiedAt.slice(0, 10)}</strong></span></div>
    <div className="trace-tabs" aria-label="Inspect a decision">{questions.map(([key, title]) => <button key={key} aria-pressed={active === key} onClick={() => { setActive(key); setShowAll(false); }}><span>{title}</span><strong>{label(trace.response.answers[key].choice)}</strong></button>)}</div>
    <div className="trace-body">
      <div className="trace-ranking">
        <div className="trace-section-label"><h3>Candidate scores</h3><span>AS RETURNED BY JEV</span></div>
        {!answer.probabilities && <p className="trace-note">The API did not return candidate probabilities for this question. No scores have been invented.</p>}
        <ol className="candidate-list">{visible.map(option => <li key={option.key} className={option.key === answer.choice ? 'candidate-selected' : ''}>
          <div className="candidate-label"><span>{option.key === answer.choice && <Check size={14} />}{label(option.key)}</span><strong>{option.probability === undefined ? 'Not returned' : percent(option.probability)}</strong></div>
          {option.probability !== undefined && <div className="candidate-track" aria-hidden="true"><span style={{ width: `${option.probability * 100}%` }} /></div>}
        </li>)}</ol>
        {options.length > 5 && <button className="trace-expand" onClick={() => setShowAll(value => !value)}>{showAll ? 'Show fewer candidates' : `See all ${options.length} candidates`}<ChevronDown size={16} /></button>}
        <p className="trace-note">Provider-reported choice probabilities, not benchmark scores or a calibrated chance of task success. Displayed values are rounded; missing values stay missing.</p>
      </div>
      <div className="trace-explanation">
        <span className="small-label">SELECTED CRITERION</span><h3>{label(answer.choice)}</h3>
        <p>{question.criteria[answer.choice]}</p>
        <div className="trace-confidence"><span>Reported confidence</span><strong>{answer.confidence === undefined ? 'Not returned' : percent(answer.confidence)}</strong></div>
        <p className="trace-note">The criterion above is the instruction we supplied for this option—not prose reasoning generated by Jev.</p>
        {(active === 'model' || active === 'budgetModel') && <p className="trace-note">Local benchmark observations are included where available: four small tasks, one sample each. Untested models are marked “not evaluated,” not ranked lower. Formatting, wrong answers, token limits and API errors remain distinct. The dated protocol is in the exact instructions below.</p>}
        {active === 'budgetModel' && <p className="budget-check"><Check size={15} />{trace.budgetDisposition === 'shown' ? 'Price check passed. Both token rates are no higher; at least one is lower. We keep the same task-required effort.' : trace.budgetDisposition === 'none' ? 'Jev selected no budget alternative.' : 'Not shown as an alternative: Jev’s budget selection is the same model or does not have lower-or-equal input and output rates.'}</p>}
        <details className="trace-policy"><summary>Exact instructions for this question <ChevronDown size={15} /></summary><p>{question.instructions}</p></details>
      </div>
    </div>
    <details className="trace-raw"><summary>Inspect the request & response <ArrowDown size={16} /></summary><p>Request body and validated response fields. No authorization headers or API keys. Your task text is included.</p><div className="raw-grid"><div><h3>Sent to Jev</h3><textarea aria-label="Exact Jev request body" readOnly value={JSON.stringify(trace.request, null, 2)} /></div><div><h3>Returned by Jev</h3><textarea aria-label="Validated Jev response" readOnly value={JSON.stringify(trace.response, null, 2)} /></div></div><p>Resolved router: <code>{trace.response.model}</code> · policy <code>{trace.policyVersion}</code>{trace.response.usage?.cost !== undefined && <> · routing API charge <code>${trace.response.usage.cost.toFixed(6)}</code></>}</p></details>
  </section>;
}
